language: objective-c
osx_image: xcode7.3
sudo: false
git:
  submodules: false
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6s"          SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="CoreStore iOS"     SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="CoreStore iOS7"    SDK=iphonesimulator9.3  RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="arch=x86_64"                    SCHEME="CoreStore OSX"     SDK=macosx10.11         RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CoreStore watchOS" SDK=watchsimulator2.2   RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="CoreStore tvOS"    SDK=appletvsimulator9.2 RUN_TESTS="YES" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
before_script:
  - carthage update --use-submodules
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then 
      xcodebuild -workspace CoreStore.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
      xcodebuild -workspace CoreStore.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
    fi
  - xcodebuild -workspace "CoreStore.xcworkspace" -scheme "CoreStore iOS" -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6s" -configuration Debug ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
  - xcodebuild -workspace "CoreStore.xcworkspace" -scheme "CoreStore iOS" -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6s" -configuration Release ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
